/**
 * Golden-file tests (data-model spec section 11): the engine's output must
 * equal the independently computed expectations for five real companies'
 * as-filed EDGAR data, at the pinned display precision, including every
 * not-meaningful and insufficient-data state and the fired red flags.
 *
 * The fixtures are generated by tools/generate-fixtures.mjs, which never
 * imports engine code; see fixtures/README.md for provenance and the
 * regeneration procedure. This file is the Phase 0 exit criterion.
 */
import { readdirSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { checkIdentities } from '../src/gates.js';
import { formatMetricValue } from '../src/format.js';
import { METRIC_IDS, METRICS } from '../src/metrics.js';
import { computeMetricsReport } from '../src/report.js';
import type {
  Basis,
  CompanyFinancials,
  FyLabel,
  LineItemId,
  MetricId,
  NotMeaningfulReason,
  StatementYear
} from '../src/index.js';

type ExpectedMetric =
  | { status: 'ok'; display: string; basis?: Basis }
  | { status: 'not_meaningful'; reason: NotMeaningfulReason }
  | { status: 'insufficient_data'; missing: LineItemId[] };

interface Fixture {
  meta: { name: string; ticker: string; currency: string };
  price: { amountMinor: number; currency: string; asOf: string };
  /** The source reference shape differs by system (EDGAR accessions; ASX documents and printed pages). */
  years: (StatementYear & { sourceRef: { system: string } & Record<string, unknown> })[];
  expected: {
    metrics: Record<MetricId, Record<FyLabel, ExpectedMetric>>;
    flags: { ruleId: string; severity: string; window: FyLabel[] }[];
  };
}

const FIXTURES_DIR = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'fixtures');
const fixtureFiles = readdirSync(FIXTURES_DIR).filter((file) => file.endsWith('.json'));

// The Phase 0 five plus the Phase 2.5 ASX corpus (spec section 11).
const EXPECTED_CORPUS = [
  'aapl.json',
  'coh.json',
  'cost.json',
  'csl.json',
  'jbh.json',
  'ko.json',
  'msft.json',
  'unp.json',
  'wes.json',
  'wow.json'
];

it('the golden corpus is present (spec section 11)', () => {
  expect(fixtureFiles.sort()).toEqual(EXPECTED_CORPUS);
});

for (const file of fixtureFiles) {
  const fixture = JSON.parse(readFileSync(path.join(FIXTURES_DIR, file), 'utf8')) as Fixture;

  describe(`golden: ${fixture.meta.name} (${fixture.meta.ticker})`, () => {
    const input: CompanyFinancials = {
      years: fixture.years.map(({ fy, endDate, currency, entryScale, values }) => ({
        fy,
        endDate,
        currency,
        entryScale,
        values
      })),
      price: fixture.price
    };
    const report = computeMetricsReport(input);

    it('carries every fixture year, in order', () => {
      expect(report.fyLabels).toEqual(fixture.years.map((year) => year.fy));
    });

    it('passes the identity gates on every as-filed year', () => {
      for (const year of input.years) {
        for (const gate of checkIdentities(year)) {
          expect.soft(gate, `${fixture.meta.ticker} ${year.fy} ${gate.gate}`).not.toMatchObject({
            status: 'fail'
          });
        }
      }
    });

    for (const metricId of METRIC_IDS) {
      it(`${METRICS[metricId].label} matches the hand computation for every year`, () => {
        for (const year of fixture.years) {
          const expected = fixture.expected.metrics[metricId][year.fy];
          const actual = report.metrics[metricId].values[year.fy];
          const label = `${fixture.meta.ticker} ${year.fy} ${metricId}`;
          expect(actual, label).toBeDefined();
          if (actual === undefined || expected === undefined) {
            throw new Error(`${label}: fixture and report disagree on coverage`);
          }
          expect.soft(actual.status, label).toBe(expected.status);
          if (expected.status === 'ok' && actual.status === 'ok') {
            const display = formatMetricValue(actual, METRICS[metricId].format, fixture.meta.currency);
            expect.soft(display, label).toBe(expected.display);
            if (expected.basis !== undefined) {
              expect.soft(actual.basis, label).toBe(expected.basis);
            }
          } else if (expected.status === 'not_meaningful' && actual.status === 'not_meaningful') {
            expect.soft(actual.reason, label).toBe(expected.reason);
          } else if (expected.status === 'insufficient_data' && actual.status === 'insufficient_data') {
            expect.soft([...actual.missing].sort(), label).toEqual([...expected.missing].sort());
          }
        }
      });
    }

    it('fires exactly the expected red flags', () => {
      const actual = report.flags
        .map(({ ruleId, severity, window }) => ({ ruleId, severity, window }))
        .sort((a, b) => a.ruleId.localeCompare(b.ruleId));
      const expected = [...fixture.expected.flags].sort((a, b) => a.ruleId.localeCompare(b.ruleId));
      expect(actual).toEqual(expected);
    });
  });
}
