/**
 * Generates src/features/library/sampleData.ts from the calc-engine golden
 * fixtures (frontend spec §4): the sample set is real, hand-verified filing
 * data, so the sample dashboard doubles as an acceptance test of the whole
 * render path. Run from apps/web with the engine built first:
 *
 *   corepack pnpm -C ../../packages/calc-engine build
 *   node tools/generate-samples.mjs
 *
 * The engine's dist is imported directly because this script runs under plain
 * node, and the workspace export points at TypeScript source.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { LINE_ITEMS } from '../../../packages/calc-engine/dist/index.js';

const here = dirname(fileURLToPath(import.meta.url));
const fixturesDir = join(here, '..', '..', '..', 'packages', 'calc-engine', 'fixtures');
const outFile = join(here, '..', 'src', 'features', 'library', 'sampleData.ts');

/**
 * The pinned sample set (data-model spec §12 sample-corpus decision, amended
 * twice on 2026-07-18 with the ASX-first steer): the ASX golden five. The US
 * trio retired when the owner scoped the product ASX-first; the same day the
 * owner amended the depth rule so the four six-year ASX fixtures join CSL's
 * ten, sparklines showing the years each fixture actually carries.
 */
const SAMPLE_SET = [
  { file: 'csl.json', id: 'sample-csl', sector: 'Healthcare' },
  { file: 'wes.json', id: 'sample-wesfarmers', sector: 'Conglomerate' },
  { file: 'wow.json', id: 'sample-woolworths', sector: 'Consumer staples' },
  { file: 'jbh.json', id: 'sample-jb-hi-fi', sector: 'Retail' },
  { file: 'coh.json', id: 'sample-cochlear', sector: 'Medical devices' }
];

const STATEMENT_KINDS = ['income', 'balance', 'cashflow'];

const companies = [];
const statements = [];
const prices = [];

for (const { file, id, sector } of SAMPLE_SET) {
  const fixture = JSON.parse(readFileSync(join(fixturesDir, file), 'utf8'));
  const { meta, price, years } = fixture;

  companies.push({
    id,
    name: meta.name,
    ticker: meta.ticker,
    exchange: meta.exchange,
    sector,
    currency: meta.currency,
    sample: true
  });

  for (const year of years) {
    const byKind = new Map(STATEMENT_KINDS.map((kind) => [kind, {}]));
    for (const [itemId, value] of Object.entries(year.values)) {
      byKind.get(LINE_ITEMS[itemId].statement)[itemId] = value;
    }
    for (const kind of STATEMENT_KINDS) {
      const values = byKind.get(kind);
      if (Object.keys(values).length === 0) continue;
      statements.push({
        companyId: id,
        fy: year.fy,
        statement: kind,
        endDate: year.endDate,
        entryScale: year.entryScale,
        values,
        provenance: {
          source: 'sample',
          recordedAt: meta.generatedAt,
          // EDGAR years point at their accession; ASX years at the annual
          // report key in the fixture's documents map.
          filing: {
            system: year.sourceRef.system,
            documentId: year.sourceRef.accessions?.[0] ?? year.sourceRef.document
          }
        }
      });
    }
  }

  prices.push({
    companyId: id,
    amountMinor: price.amountMinor,
    currency: price.currency,
    asOf: price.asOf
  });
}

const render = (value) => JSON.stringify(value, null, 2);

const content = `/**
 * GENERATED by tools/generate-samples.mjs from the calc-engine golden
 * fixtures; regenerate rather than edit. The sample set is real,
 * hand-verified filing data (frontend spec §4), flagged sample throughout
 * and removable in one action. Prices are the fixtures' synthetic ones,
 * chosen to exercise the valuation metrics; they are not market data.
 */
import type { CompanyRecord, PriceRecord, StatementRecord } from '../../db';

export type SampleCompany = Omit<CompanyRecord, 'createdAt' | 'updatedAt' | 'dataVersion'>;
export type SampleStatement = Omit<StatementRecord, 'updatedAt'>;
export type SamplePrice = Omit<PriceRecord, 'updatedAt'>;

export const SAMPLE_COMPANIES: readonly SampleCompany[] = ${render(companies)};

export const SAMPLE_STATEMENTS: readonly SampleStatement[] = ${render(statements)};

export const SAMPLE_PRICES: readonly SamplePrice[] = ${render(prices)};
`;

writeFileSync(outFile, content);
console.log(
  `Wrote ${outFile}: ${companies.length} companies, ${statements.length} statement rows, ${prices.length} prices.`
);
