/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as PairsIndexRouteImport } from './routes/pairs.index'
import { Route as SettingsProvidersRouteImport } from './routes/settings.providers'
import { Route as SettingsDataRouteImport } from './routes/settings.data'
import { Route as PairsBacktestRouteImport } from './routes/pairs.backtest'
import { Route as CompanyIdIndexRouteImport } from './routes/company.$id.index'
import { Route as CompanyIdThesisRouteImport } from './routes/company.$id.thesis'
import { Route as CompanyIdEntryRouteImport } from './routes/company.$id.entry'

const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const PairsIndexRoute = PairsIndexRouteImport.update({
  id: '/pairs/',
  path: '/pairs/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProvidersRoute = SettingsProvidersRouteImport.update({
  id: '/settings/providers',
  path: '/settings/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsDataRoute = SettingsDataRouteImport.update({
  id: '/settings/data',
  path: '/settings/data',
  getParentRoute: () => rootRouteImport,
} as any)
const PairsBacktestRoute = PairsBacktestRouteImport.update({
  id: '/pairs/backtest',
  path: '/pairs/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyIdIndexRoute = CompanyIdIndexRouteImport.update({
  id: '/company/$id/',
  path: '/company/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyIdThesisRoute = CompanyIdThesisRouteImport.update({
  id: '/company/$id/thesis',
  path: '/company/$id/thesis',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyIdEntryRoute = CompanyIdEntryRouteImport.update({
  id: '/company/$id/entry',
  path: '/company/$id/entry',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/pairs/backtest': typeof PairsBacktestRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/pairs/': typeof PairsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/company/$id/entry': typeof CompanyIdEntryRoute
  '/company/$id/thesis': typeof CompanyIdThesisRoute
  '/company/$id/': typeof CompanyIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/pairs/backtest': typeof PairsBacktestRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/pairs': typeof PairsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/company/$id/entry': typeof CompanyIdEntryRoute
  '/company/$id/thesis': typeof CompanyIdThesisRoute
  '/company/$id': typeof CompanyIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/pairs/backtest': typeof PairsBacktestRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/pairs/': typeof PairsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/company/$id/entry': typeof CompanyIdEntryRoute
  '/company/$id/thesis': typeof CompanyIdThesisRoute
  '/company/$id/': typeof CompanyIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/pairs/backtest'
    | '/settings/data'
    | '/settings/providers'
    | '/pairs/'
    | '/settings/'
    | '/company/$id/entry'
    | '/company/$id/thesis'
    | '/company/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/pairs/backtest'
    | '/settings/data'
    | '/settings/providers'
    | '/pairs'
    | '/settings'
    | '/company/$id/entry'
    | '/company/$id/thesis'
    | '/company/$id'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/pairs/backtest'
    | '/settings/data'
    | '/settings/providers'
    | '/pairs/'
    | '/settings/'
    | '/company/$id/entry'
    | '/company/$id/thesis'
    | '/company/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  PairsBacktestRoute: typeof PairsBacktestRoute
  SettingsDataRoute: typeof SettingsDataRoute
  SettingsProvidersRoute: typeof SettingsProvidersRoute
  PairsIndexRoute: typeof PairsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  CompanyIdEntryRoute: typeof CompanyIdEntryRoute
  CompanyIdThesisRoute: typeof CompanyIdThesisRoute
  CompanyIdIndexRoute: typeof CompanyIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pairs/': {
      id: '/pairs/'
      path: '/pairs'
      fullPath: '/pairs/'
      preLoaderRoute: typeof PairsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/providers': {
      id: '/settings/providers'
      path: '/settings/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof SettingsProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/data': {
      id: '/settings/data'
      path: '/settings/data'
      fullPath: '/settings/data'
      preLoaderRoute: typeof SettingsDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pairs/backtest': {
      id: '/pairs/backtest'
      path: '/pairs/backtest'
      fullPath: '/pairs/backtest'
      preLoaderRoute: typeof PairsBacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/$id/': {
      id: '/company/$id/'
      path: '/company/$id'
      fullPath: '/company/$id/'
      preLoaderRoute: typeof CompanyIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/$id/thesis': {
      id: '/company/$id/thesis'
      path: '/company/$id/thesis'
      fullPath: '/company/$id/thesis'
      preLoaderRoute: typeof CompanyIdThesisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/$id/entry': {
      id: '/company/$id/entry'
      path: '/company/$id/entry'
      fullPath: '/company/$id/entry'
      preLoaderRoute: typeof CompanyIdEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  PairsBacktestRoute: PairsBacktestRoute,
  SettingsDataRoute: SettingsDataRoute,
  SettingsProvidersRoute: SettingsProvidersRoute,
  PairsIndexRoute: PairsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  CompanyIdEntryRoute: CompanyIdEntryRoute,
  CompanyIdThesisRoute: CompanyIdThesisRoute,
  CompanyIdIndexRoute: CompanyIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
